language: c
matrix:
    include:
        - os: linux
          dist: trusty
          group: stable
        - os: osx
          osx_image: xcode8
        - os: osx
          osx_image: xcode7.3
install:
    - make
script:
    - export PATH=$(pwd)/bin:$PATH
    - indelible-ngsphy
