language: c
matrix:
    include:
        - os: linux
          dist: trusty
          group: stable
         - os: linux
          dist: xenial 
          group: stable
        - os: osx
          osx_image: xcode8
        - os: osx
          osx_image: xcode7.3
script: make
